wandb_version: 1

batched_inference:
  desc: null
  value: false
method:
  desc: null
  value: open_generation
pretrained_model_name:
  desc: null
  value: TinyLlama/TinyLlama-1.1B-Chat-v1.0
num_iteration:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716761927
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      - 71
      - 75
      2:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      - 71
      - 75
      3:
      - 2
      - 16
      - 23
      4: 3.11.4
      5: 0.17.0
      6: 4.36.2
      8:
      - 4
      - 5
      13: darwin-arm64
